import React, { useMemo } from "react"; // Import React, useState, useMemo
import {
  AlertCircleIcon,
  DownloadIcon,
  FileArchiveIcon,
  FileIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
  HeadphonesIcon,
  ImageIcon,
  Trash2Icon,
  UploadCloudIcon,
  UploadIcon,
  VideoIcon,
  LucideIcon, // Import LucideIcon type
} from "lucide-react";

import getMimeTypes from "@/lib/fileExtensions"; // Assuming this function returns a string or array of strings
import { formatBytes, useFileUpload } from "@/hooks/use-file-upload"; // Assuming useFileUpload hook is available and typed
import { Button } from "@/Components/BaseComponents/ui/button"; // Assuming Button has been converted
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/Components/BaseComponents/ui/table"; // Assuming table components are available and typed

// Define the structure for the file objects managed by useFileUpload
// This accommodates both File objects and the structure from initialFiles
interface UploadedFile {
  id: string; // Unique identifier for the file
  file:
    | File
    | {
        // The actual file data or a representation
        name: string;
        size: number;
        type: string;
        url?: string; // Optional URL for initial files
      };
  preview?: string; // Optional preview URL generated by the hook
  // Add other properties returned by useFileUpload if necessary (e.g., status, progress)
}

// Define the structure for the errors returned by useFileUpload
interface FileUploadError {
  type: string; // Type of error (e.g., 'maxSize', 'maxFiles', 'accept')
  message: string; // User-friendly error message
  file?: File; // The file that caused the error (optional)
}

// Define the structure for the icon map entries
interface IconMapEntry {
  icon: LucideIcon; // The Lucide icon component
  conditions: (type: string, name: string) => boolean; // Function to determine if the icon applies
}

// Define the props for the TableFileUploader component
interface TableFileUploaderProps {
  /**
   * The accepted file types. Can be a comma-separated string or an array of MIME types or file extensions.
   * Defaults to '*'.
   */
  accept?: string; // Optional accept prop
}

// Helper function to get the appropriate icon based on file type and name
const getFileIcon = (file: UploadedFile): React.ReactNode => {
  // Determine file type and name, handling both File instances and initial file objects
  const fileType = file.file instanceof File ? file.file.type : file.file.type;
  const fileName = file.file instanceof File ? file.file.name : file.file.name;

  // Define the map of file types to icons and their conditions
  const iconMap: { [key: string]: IconMapEntry } = {
    pdf: {
      icon: FileTextIcon,
      conditions: (type, name) =>
        type.includes("pdf") ||
        name.endsWith(".pdf") ||
        type.includes("word") || // Including word types here as in original
        name.endsWith(".doc") ||
        name.endsWith(".docx"),
    },
    archive: {
      icon: FileArchiveIcon,
      conditions: (type, name) =>
        type.includes("zip") || type.includes("archive") || name.endsWith(".zip") || name.endsWith(".rar"),
    },
    excel: {
      icon: FileSpreadsheetIcon,
      conditions: (type, name) => type.includes("excel") || name.endsWith(".xls") || name.endsWith(".xlsx"),
    },
    video: {
      icon: VideoIcon,
      conditions: (type) => type.includes("video/"),
    },
    audio: {
      icon: HeadphonesIcon,
      conditions: (type) => type.includes("audio/"),
    },
    image: {
      icon: ImageIcon,
      conditions: (type) => type.startsWith("image/"),
    },
  };

  // Iterate through the icon map and return the first matching icon
  for (const { icon: Icon, conditions } of Object.values(iconMap)) {
    if (conditions(fileType, fileName)) {
      return <Icon className="size-4 opacity-60" />;
    }
  }

  // Return a generic file icon if no specific match is found
  return <FileIcon className="size-4 opacity-60" />;
};

/**
 * A file uploader component that displays uploaded files in a table.
 * It includes drag and drop functionality and error handling, utilizing the `useFileUpload` hook.
 *
 * @param {TableFileUploaderProps} param0 The component's props.
 * @param {string | string[]} [param0.accept='*'] The accepted file types.
 * @returns {React.FC} A React functional component for the file uploader table.
 */
const TableFileUploader: React.FC<TableFileUploaderProps> = ({ accept = "*" }) => {
  // Process the accept prop using getMimeTypes
  const newAccept = useMemo(() => getMimeTypes(accept), [accept]);

  // Define max file size and count
  const maxSize = 10 * 1024 * 1024; // 10MB default
  const maxFiles = 10;

  // Define some dummy initial files with the correct type structure for useFileUpload
  const initialFiles: { id: string; url: string }[] = [
    {
      id: "document.pdf-1744638436563-8u5xuls",
      url: "https://originui.com",
    },
    {
      id: "intro.zip-1744638436563-8u5xuls",
      url: "https://originui.com",
    },
    {
      id: "conclusion.xlsx-1744638436563-8u5xuls",
      url: "https://originui.com",
    },
  ];

  // Use the useFileUpload hook with explicit types for files and errors
  const fileUploadResult = useFileUpload({
    multiple: true,
    maxFiles,
    maxSize,
    initialFiles,
    accept: newAccept,
  });

  // Narrow the result to the expected tuple structure
  const [
    { files, isDragging, errors },
    {
      handleDragEnter,
      handleDragLeave,
      handleDragOver,
      handleDrop,
      openFileDialog,
      removeFile,
      clearFiles,
      getInputProps,
    },
  ] = fileUploadResult as unknown as [
    { files: UploadedFile[]; isDragging: boolean; errors: FileUploadError[] },
    {
      handleDragEnter: React.DragEventHandler<HTMLDivElement>;
      handleDragLeave: React.DragEventHandler<HTMLDivElement>;
      handleDragOver: React.DragEventHandler<HTMLDivElement>;
      handleDrop: React.DragEventHandler<HTMLDivElement>;
      openFileDialog: () => void;
      removeFile: (id: string) => void;
      clearFiles: () => void;
      getInputProps: (
        props?: React.InputHTMLAttributes<HTMLInputElement>
      ) => React.InputHTMLAttributes<HTMLInputElement>;
    }
  ];


  return (
    <div className="flex flex-col gap-2">
      {/* Drop area - hidden when files are present */}
      <div
        onDragEnter={handleDragEnter}
        onDragLeave={handleDragLeave}
        onDragOver={handleDragOver}
        onDrop={handleDrop}
        data-dragging={isDragging || undefined}
        data-files={files.length > 0 || undefined}
        className="border-input data-[dragging=true]:bg-accent/50 has-[input:focus]:border-ring has-[input:focus]:ring-ring/50 flex min-h-56 flex-col items-center rounded-xl border border-dashed p-4 transition-colors not-data-[files]:justify-center has-[input:focus]:ring-[3px] data-[files]:hidden"
      >
        {/* Hidden input for file selection */}
        <input {...getInputProps()} className="sr-only" aria-label="Upload files" />
        <div className="flex flex-col items-center justify-center text-center">
          <div
            className="bg-background mb-2 flex size-11 shrink-0 items-center justify-center rounded-full border"
            aria-hidden="true"
          >
            <FileIcon className="size-4 opacity-60" />
          </div>
          <p className="mb-1.5 text-sm font-medium">Upload files</p>
          <p className="text-muted-foreground text-xs">
            Max {maxFiles} files ∙ Up to {formatBytes(maxSize)}
          </p>
          {/* Button to open file dialog */}
          <Button variant="outline" className="mt-4" onClick={openFileDialog}>
            <UploadIcon className="-ms-1 opacity-60" aria-hidden="true" />
            Select files
          </Button>
        </div>
      </div>

      {/* Render table if files exist */}
      {files.length > 0 && (
        <>
          {/* Header and action buttons for the file table */}
          <div className="flex items-center justify-between gap-2">
            <h3 className="text-sm font-medium">Files ({files.length})</h3>
            <div className="flex gap-2">
              {/* Add files button */}
              <Button variant="outline" size="sm" onClick={openFileDialog}>
                <UploadCloudIcon className="-ms-0.5 size-3.5 opacity-60" aria-hidden="true" />
                Add files
              </Button>
              {/* Remove all files button */}
              <Button variant="outline" size="sm" onClick={clearFiles}>
                <Trash2Icon className="-ms-0.5 size-3.5 opacity-60" aria-hidden="true" />
                Remove all
              </Button>
            </div>
          </div>
          {/* File table */}
          <div className="bg-background overflow-hidden rounded-md border">
            <Table>
              <TableHeader className="text-xs">
                <TableRow className="bg-muted/50">
                  <TableHead className="h-9 py-2">Name</TableHead>
                  <TableHead className="h-9 py-2">Type</TableHead>
                  <TableHead className="h-9 py-2">Size</TableHead>
                  <TableHead className="h-9 w-0 py-2 text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody className="text-[13px]">
                {files.map((file) => (
                  <TableRow key={file.id}>
                    <TableCell className="max-w-48 py-2 font-medium">
                      <span className="flex items-center gap-2">
                        <span className="shrink-0">{getFileIcon(file)}</span>{" "}
                        <span className="truncate">{file.file.name}</span>
                      </span>
                    </TableCell>
                    <TableCell className="text-muted-foreground py-2">
                      {/* Display file type, handling potential undefined split result */}
                      {file.file.type.split("/")[1]?.toUpperCase() || "UNKNOWN"}
                    </TableCell>
                    <TableCell className="text-muted-foreground py-2">{formatBytes(file.file.size)}</TableCell>
                    <TableCell className="py-2 text-right whitespace-nowrap">
                      {/* Download button - opens preview URL in a new tab */}
                      <Button
                        size="icon"
                        variant="ghost"
                        className="text-muted-foreground/80 hover:text-foreground size-8 hover:bg-transparent"
                        aria-label={`Download ${file.file.name}`}
                        // Ensure file.preview exists before opening
                        onClick={() => file.preview && window.open(file.preview, "_blank")}
                        disabled={!file.preview} // Disable button if no preview URL
                      >
                        <DownloadIcon className="size-4" />
                      </Button>
                      {/* Remove button */}
                      <Button
                        size="icon"
                        variant="ghost"
                        className="text-muted-foreground/80 hover:text-foreground size-8 hover:bg-transparent"
                        aria-label={`Remove ${file.file.name}`}
                        onClick={() => removeFile(file.id)}
                      >
                        <Trash2Icon className="size-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </>
      )}

      {/* Display errors */}
      {errors.length > 0 && (
        <div className="text-destructive flex items-center gap-1 text-xs" role="alert">
          <AlertCircleIcon className="size-3 shrink-0" />
          {/* Display the message of the first error */}
          <span>{errors[0].message}</span>
        </div>
      )}
      {/* Commented out section as in original */}
      {/* <p
                aria-live="polite"
                role="region"
                className="text-muted-foreground mt-2 text-center text-xs">
                Multiple files uploader w/ table ∙{" "}
                <a
                    href="https://github.com/origin-space/originui/tree/main/docs/use-file-upload.md"
                    className="hover:text-foreground underline">
                    API
                </a>
            </p> */}
    </div>
  );
};

export default TableFileUploader;
